INSERT INTO `parameter` (`parameter_id`, `name`, `type`, `description`, `default_value`, `skip_last_parameter_overview`) VALUES
(38, 'lock_name_space', 2, 'lock name space used for generating lock names for standby/clone database', '', 'false'),
(39, 'processes', 3, 'user processes', '100', 'false'),
(40, 'sessions', 3, 'user and system sessions', '115', 'false'),
(41, 'timed_statistics', 1, 'maintain internal timing statistics', 'TRUE', 'false'),
(42, 'timed_os_statistics', 3, 'internal os statistic gathering interval in seconds', '0', 'false'),
(43, 'resource_limit', 1, 'master switch for resource limit', 'FALSE', 'false'),
(44, 'license_max_sessions', 3, 'maximum number of non-system user sessions allowed', '0', 'false'),
(45, 'license_sessions_warning', 3, 'warning level for number of non-system user sessions', '0', 'false'),
(86, 'cpu_count', 3, 'number of CPUs for this instance', '8', 'false'),
(91, 'instance_groups', 2, 'list of instance group names', '', 'false'),
(95, 'event', 2, 'debug event control - default null string', '', 'false'),
(107, 'sga_max_size', 6, 'max total SGA size', '', 'false'),
(114, 'use_large_pages', 2, 'Use large pages if available (TRUE/FALSE/ONLY)', 'TRUE', 'false'),
(116, 'pre_page_sga', 1, 'pre-page sga for process', 'FALSE', 'false'),
(117, 'shared_memory_address', 3, 'SGA starting address (low order 32-bits on 64-bit platforms)', '0', 'false'),
(118, 'hi_shared_memory_address', 3, 'SGA starting address (high order 32-bits on 64-bit platforms)', '0', 'false'),
(119, 'use_indirect_data_buffers', 1, 'Enable indirect data buffers (very large SGA on 32-bit platforms)', 'FALSE', 'false'),
(121, 'lock_sga', 1, 'Lock entire SGA in physical memory', 'FALSE', 'false'),
(162, 'processor_group_name', 2, 'Name of the processor group that this instance should run in.', '', 'false'),
(164, 'shared_pool_size', 6, 'size in bytes of shared pool', '0', 'false'),
(166, 'large_pool_size', 6, 'size in bytes of large pool', '0', 'false'),
(168, 'java_pool_size', 6, 'size in bytes of java pool', '0', 'false'),
(170, 'streams_pool_size', 6, 'size in bytes of the streams pool', '0', 'false'),
(172, 'shared_pool_reserved_size', 6, 'size in bytes of reserved area of shared pool', '92274688', 'false'),
(175, 'java_soft_sessionspace_limit', 3, 'warning limit on size in bytes of a Java sessionspace', '0', 'false'),
(176, 'java_max_sessionspace_size', 3, 'max allowed size in bytes of a Java sessionspace', '0', 'false'),
(184, 'spfile', 2, 'server parameter file', '/u01/app/oracle/product/rdbms/11.2.0.3.2/dbs/spfilep372.ora', 'false'),
(185, 'instance_type', 2, 'type of instance to be executed', 'RDBMS', 'false'),
(222, 'nls_language', 2, 'NLS language name', 'AMERICAN', 'false'),
(223, 'nls_territory', 2, 'NLS territory name', 'AMERICA', 'false'),
(224, 'nls_sort', 2, 'NLS linguistic definition name', 'BINARY', 'false'),
(225, 'nls_date_language', 2, 'NLS date language name', 'AMERICAN', 'false'),
(226, 'nls_date_format', 2, 'NLS Oracle date format', 'DD-MON-RR', 'false'),
(227, 'nls_currency', 2, 'NLS local currency symbol', '$', 'false'),
(228, 'nls_numeric_characters', 2, 'NLS numeric characters', '.,', 'false'),
(229, 'nls_iso_currency', 2, 'NLS ISO currency territory name', 'AMERICA', 'false'),
(230, 'nls_calendar', 2, 'NLS calendar system name', 'GREGORIAN', 'false'),
(231, 'nls_time_format', 2, 'time format', 'HH.MI.SSXFF AM', 'false'),
(232, 'nls_timestamp_format', 2, 'time stamp format', 'DD-MON-RR HH.MI.SSXFF AM', 'false'),
(233, 'nls_time_tz_format', 2, 'time with timezone format', 'HH.MI.SSXFF AM TZR', 'false'),
(234, 'nls_timestamp_tz_format', 2, 'timestamp with timezone format', 'DD-MON-RR HH.MI.SSXFF AM TZR', 'false'),
(235, 'nls_dual_currency', 2, 'Dual currency symbol', '$', 'false'),
(236, 'nls_comp', 2, 'NLS comparison', 'BINARY', 'false'),
(237, 'nls_length_semantics', 2, 'create columns using byte or char semantics by default', 'BYTE', 'false'),
(238, 'nls_nchar_conv_excp', 2, 'NLS raise an exception instead of allowing implicit conversion', 'FALSE', 'false'),
(244, 'fileio_network_adapters', 2, 'Network Adapters for File I/O', '', 'false'),
(246, 'filesystemio_options', 2, 'IO operations on filesystem files', '', 'false'),
(257, 'clonedb', 1, 'clone database', 'FALSE', 'false'),
(264, 'disk_asynch_io', 1, 'Use asynch I/O for random access devices', 'TRUE', 'false'),
(265, 'tape_asynch_io', 1, 'Use asynch I/O requests for tape devices', 'TRUE', 'false'),
(267, 'dbwr_io_slaves', 3, 'DBWR I/O slaves', '0', 'false'),
(271, 'backup_tape_io_slaves', 1, 'BACKUP Tape I/O slaves', 'FALSE', 'false'),
(279, 'resource_manager_cpu_allocation', 3, 'Resource Manager CPU allocation', '8', 'false'),
(281, 'resource_manager_plan', 2, 'resource mgr top plan', '', 'true'),
(338, 'cluster_interconnects', 2, 'interconnects for RAC use', '', 'false'),
(401, 'file_mapping', 1, 'enable file mapping', 'FALSE', 'false'),
(488, 'gcs_server_processes', 3, 'number of background gcs server processes to start', '0', 'false'),
(500, 'active_instance_count', 3, 'number of active instances in the cluster database', '', 'false'),
(711, 'sga_target', 6, 'Target size of SGA', '', 'false'),
(713, 'memory_target', 6, 'Target size of Oracle SGA and PGA memory', '0', 'false'),
(714, 'memory_max_target', 6, 'Max size for Memory Target', '0', 'false'),
(740, 'control_files', 2, 'control file names list', '', 'false'),
(749, 'db_file_name_convert', 2, 'datafile name convert patterns and strings for standby/clone db', '', 'false'),
(750, 'log_file_name_convert', 2, 'logfile name convert patterns and strings for standby/clone db', '', 'false'),
(751, 'control_file_record_keep_time', 3, 'control file record keep time in days', '7', 'false'),
(754, 'db_block_buffers', 3, 'Number of database blocks cached in memory', '0', 'false'),
(758, 'db_block_checksum', 2, 'store checksum in db blocks and check during reads', 'TYPICAL', 'false'),
(759, 'db_ultra_safe', 2, 'Sets defaults for other parameters that control protection levels', 'OFF', 'false'),
(760, 'db_block_size', 3, 'Size of database block in bytes', '8192', 'false'),
(776, 'db_cache_size', 6, 'Size of DEFAULT buffer pool for standard block size buffers', '0', 'false'),
(778, 'db_2k_cache_size', 6, 'Size of cache for 2K buffers', '0', 'false'),
(779, 'db_4k_cache_size', 6, 'Size of cache for 4K buffers', '0', 'false'),
(780, 'db_8k_cache_size', 6, 'Size of cache for 8K buffers', '0', 'false'),
(781, 'db_16k_cache_size', 6, 'Size of cache for 16K buffers', '0', 'false'),
(782, 'db_32k_cache_size', 6, 'Size of cache for 32K buffers', '0', 'false'),
(783, 'db_keep_cache_size', 6, 'Size of KEEP buffer pool for standard block size buffers', '0', 'false'),
(784, 'db_recycle_cache_size', 6, 'Size of RECYCLE buffer pool for standard block size buffers', '0', 'false'),
(796, 'db_writer_processes', 3, 'number of background database writer  processes to start', '1', 'false'),
(817, 'buffer_pool_keep', 2, 'Number of database blocks/latches in keep buffer pool', '', 'false'),
(818, 'buffer_pool_recycle', 2, 'Number of database blocks/latches in recycle buffer pool', '', 'false'),
(870, 'db_flash_cache_file', 2, 'flash cache file for default block size', '', 'false'),
(871, 'db_flash_cache_size', 6, 'flash cache size for db_flash_cache_file', '0', 'false'),
(889, 'db_cache_advice', 2, 'Buffer cache sizing advisory', 'ON', 'false'),
(904, 'compatible', 2, 'Database will be completely compatible with this software version', '', 'false'),
(915, 'log_archive_dest_1', 2, 'archival destination #1 text string', '', 'false'),
(916, 'log_archive_dest_2', 2, 'archival destination #2 text string', '', 'false'),
(917, 'log_archive_dest_3', 2, 'archival destination #3 text string', '', 'false'),
(918, 'log_archive_dest_4', 2, 'archival destination #4 text string', '', 'false'),
(919, 'log_archive_dest_5', 2, 'archival destination #5 text string', '', 'false'),
(920, 'log_archive_dest_6', 2, 'archival destination #6 text string', '', 'false'),
(921, 'log_archive_dest_7', 2, 'archival destination #7 text string', '', 'false'),
(922, 'log_archive_dest_8', 2, 'archival destination #8 text string', '', 'false'),
(923, 'log_archive_dest_9', 2, 'archival destination #9 text string', '', 'false'),
(924, 'log_archive_dest_10', 2, 'archival destination #10 text string', '', 'false'),
(925, 'log_archive_dest_11', 2, 'archival destination #11 text string', '', 'false'),
(926, 'log_archive_dest_12', 2, 'archival destination #12 text string', '', 'false'),
(927, 'log_archive_dest_13', 2, 'archival destination #13 text string', '', 'false'),
(928, 'log_archive_dest_14', 2, 'archival destination #14 text string', '', 'false'),
(929, 'log_archive_dest_15', 2, 'archival destination #15 text string', '', 'false'),
(930, 'log_archive_dest_16', 2, 'archival destination #16 text string', '', 'false'),
(931, 'log_archive_dest_17', 2, 'archival destination #17 text string', '', 'false'),
(932, 'log_archive_dest_18', 2, 'archival destination #18 text string', '', 'false'),
(933, 'log_archive_dest_19', 2, 'archival destination #19 text string', '', 'false'),
(934, 'log_archive_dest_20', 2, 'archival destination #20 text string', '', 'false'),
(935, 'log_archive_dest_21', 2, 'archival destination #21 text string', '', 'false'),
(936, 'log_archive_dest_22', 2, 'archival destination #22 text string', '', 'false'),
(937, 'log_archive_dest_23', 2, 'archival destination #23 text string', '', 'false'),
(938, 'log_archive_dest_24', 2, 'archival destination #24 text string', '', 'false'),
(939, 'log_archive_dest_25', 2, 'archival destination #25 text string', '', 'false'),
(940, 'log_archive_dest_26', 2, 'archival destination #26 text string', '', 'false'),
(941, 'log_archive_dest_27', 2, 'archival destination #27 text string', '', 'false'),
(942, 'log_archive_dest_28', 2, 'archival destination #28 text string', '', 'false'),
(943, 'log_archive_dest_29', 2, 'archival destination #29 text string', '', 'false'),
(944, 'log_archive_dest_30', 2, 'archival destination #30 text string', '', 'false'),
(945, 'log_archive_dest_31', 2, 'archival destination #31 text string', '', 'false'),
(946, 'log_archive_dest_state_1', 2, 'archival destination #1 state text string', '', 'false'),
(947, 'log_archive_dest_state_2', 2, 'archival destination #2 state text string', '', 'false'),
(948, 'log_archive_dest_state_3', 2, 'archival destination #3 state text string', 'enable', 'false'),
(949, 'log_archive_dest_state_4', 2, 'archival destination #4 state text string', 'enable', 'false'),
(950, 'log_archive_dest_state_5', 2, 'archival destination #5 state text string', 'enable', 'false'),
(951, 'log_archive_dest_state_6', 2, 'archival destination #6 state text string', 'enable', 'false'),
(952, 'log_archive_dest_state_7', 2, 'archival destination #7 state text string', 'enable', 'false'),
(953, 'log_archive_dest_state_8', 2, 'archival destination #8 state text string', 'enable', 'false'),
(954, 'log_archive_dest_state_9', 2, 'archival destination #9 state text string', 'enable', 'false'),
(955, 'log_archive_dest_state_10', 2, 'archival destination #10 state text string', 'enable', 'false'),
(956, 'log_archive_dest_state_11', 2, 'archival destination #11 state text string', 'enable', 'false'),
(957, 'log_archive_dest_state_12', 2, 'archival destination #12 state text string', 'enable', 'false'),
(958, 'log_archive_dest_state_13', 2, 'archival destination #13 state text string', 'enable', 'false'),
(959, 'log_archive_dest_state_14', 2, 'archival destination #14 state text string', 'enable', 'false'),
(960, 'log_archive_dest_state_15', 2, 'archival destination #15 state text string', 'enable', 'false'),
(961, 'log_archive_dest_state_16', 2, 'archival destination #16 state text string', 'enable', 'false'),
(962, 'log_archive_dest_state_17', 2, 'archival destination #17 state text string', 'enable', 'false'),
(963, 'log_archive_dest_state_18', 2, 'archival destination #18 state text string', 'enable', 'false'),
(964, 'log_archive_dest_state_19', 2, 'archival destination #19 state text string', 'enable', 'false'),
(965, 'log_archive_dest_state_20', 2, 'archival destination #20 state text string', 'enable', 'false'),
(966, 'log_archive_dest_state_21', 2, 'archival destination #21 state text string', 'enable', 'false'),
(967, 'log_archive_dest_state_22', 2, 'archival destination #22 state text string', 'enable', 'false'),
(968, 'log_archive_dest_state_23', 2, 'archival destination #23 state text string', 'enable', 'false'),
(969, 'log_archive_dest_state_24', 2, 'archival destination #24 state text string', 'enable', 'false'),
(970, 'log_archive_dest_state_25', 2, 'archival destination #25 state text string', 'enable', 'false'),
(971, 'log_archive_dest_state_26', 2, 'archival destination #26 state text string', 'enable', 'false'),
(972, 'log_archive_dest_state_27', 2, 'archival destination #27 state text string', 'enable', 'false'),
(973, 'log_archive_dest_state_28', 2, 'archival destination #28 state text string', 'enable', 'false'),
(974, 'log_archive_dest_state_29', 2, 'archival destination #29 state text string', 'enable', 'false'),
(975, 'log_archive_dest_state_30', 2, 'archival destination #30 state text string', 'enable', 'false'),
(976, 'log_archive_dest_state_31', 2, 'archival destination #31 state text string', 'enable', 'false'),
(977, 'log_archive_start', 1, 'start archival process on SGA initialization', 'FALSE', 'false'),
(978, 'log_archive_dest', 2, 'archival destination text string', '', 'false'),
(979, 'log_archive_duplex_dest', 2, 'duplex archival destination text string', '', 'false'),
(980, 'log_archive_min_succeed_dest', 3, 'minimum number of archive destinations that must succeed', '', 'false'),
(981, 'standby_archive_dest', 2, 'standby database archivelog destination text string', '?/dbs/arch', 'false'),
(986, 'fal_client', 2, 'FAL client', '', 'false'),
(987, 'fal_server', 2, 'FAL server list', '', 'false'),
(990, 'log_archive_trace', 3, 'Establish archivelog operation tracing level', '0', 'false'),
(1006, 'log_archive_config', 2, 'log archive config parameter', 'SEND, RECEIVE, NODG_CONFIG', 'false'),
(1011, 'log_archive_local_first', 1, 'Establish EXPEDITE attribute default value', 'TRUE', 'false'),
(1013, 'log_archive_format', 2, 'archival destination format', '4', 'false'),
(1017, 'redo_transport_user', 2, 'Data Guard transport user when using password file', '', 'false'),
(1022, 'log_archive_max_processes', 3, 'maximum number of active ARCH processes', '4', 'false'),
(1035, 'log_buffer', 3, 'redo circular buffer size', '11665408', 'false'),
(1038, 'log_checkpoint_interval', 3, '# redo blocks checkpoint threshold', '0', 'false'),
(1039, 'log_checkpoint_timeout', 3, 'Maximum time interval between checkpoints in seconds', '1800', 'false'),
(1041, 'archive_lag_target', 3, 'Maximum number of seconds of redos the standby could lose', '', 'false'),
(1072, 'db_files', 3, 'max allowable # db files', '200', 'false'),
(1073, 'db_file_multiblock_read_count', 3, 'db block to be read each IO', '128', 'false'),
(1077, 'read_only_open_delayed', 1, 'if TRUE delay opening of read only files until first access', 'FALSE', 'false'),
(1078, 'cluster_database', 1, 'if TRUE startup in cluster database mode', '', 'false'),
(1079, 'parallel_server', 1, 'if TRUE startup in parallel server mode', 'FALSE', 'false'),
(1080, 'parallel_server_instances', 3, 'number of instances to use for sizing OPS SGA structures', '1', 'false'),
(1081, 'cluster_database_instances', 3, 'number of instances to use for sizing cluster db SGA structures', '1', 'false'),
(1082, 'db_create_file_dest', 2, 'default database location', '', 'false'),
(1083, 'db_create_online_log_dest_1', 2, 'online log/controlfile destination #1', '', 'false'),
(1084, 'db_create_online_log_dest_2', 2, 'online log/controlfile destination #2', '', 'false'),
(1085, 'db_create_online_log_dest_3', 2, 'online log/controlfile destination #3', '', 'false'),
(1086, 'db_create_online_log_dest_4', 2, 'online log/controlfile destination #4', '', 'false'),
(1087, 'db_create_online_log_dest_5', 2, 'online log/controlfile  destination #5', '', 'false'),
(1088, 'db_recovery_file_dest', 2, 'default database recovery file location', '', 'false'),
(1089, 'db_recovery_file_dest_size', 6, 'database recovery files size limit', '', 'false'),
(1091, 'standby_file_management', 2, 'if auto then files are created/dropped automatically on standby', 'MANUAL', 'false'),
(1169, 'db_unrecoverable_scn_tracking', 1, 'Track nologging SCN in controlfile', 'TRUE', 'false'),
(1173, 'thread', 3, 'Redo thread to mount', '0', 'false'),
(1180, 'fast_start_io_target', 3, 'Upper bound on recovery reads', '0', 'false'),
(1181, 'fast_start_mttr_target', 3, 'MTTR target in seconds', '0', 'false'),
(1187, 'log_checkpoints_to_alert', 1, 'log checkpoint begin/end to alert file', 'FALSE', 'false'),
(1188, 'db_lost_write_protect', 2, 'enable lost write detection', 'NONE', 'false'),
(1190, 'recovery_parallelism', 3, 'number of server processes to use for parallel recovery', '0', 'false'),
(1274, 'db_flashback_retention_target', 3, 'Maximum Flashback Database log retention time in minutes.', '', 'false'),
(1367, 'dml_locks', 3, 'dml locks - one for each table modified in a transaction', '4116', 'false'),
(1372, 'replication_dependency_tracking', 1, 'tracking dependency for Replication parallel propagation', 'TRUE', 'false'),
(1380, 'transactions', 3, 'max. number of concurrent active transactions', '1029', 'false'),
(1381, 'transactions_per_rollback_segment', 3, 'number of active transactions per rollback segment', '5', 'false'),
(1383, 'rollback_segments', 2, 'undo segment list', '', 'false'),
(1391, 'undo_management', 2, 'instance runs in SMU mode if TRUE, else in RBU mode', 'AUTO', 'false'),
(1392, 'undo_tablespace', 2, 'use/switch undo tablespace', '', 'false'),
(1409, 'undo_retention', 3, 'undo retention in seconds', '', 'false'),
(1412, 'fast_start_parallel_rollback', 2, 'max number of parallel recovery slaves that may be used', 'LOW', 'false'),
(1414, 'resumable_timeout', 3, 'set resumable_timeout', '0', 'false'),
(1432, 'instance_number', 3, 'instance number', '0', 'false'),
(1482, 'db_block_checking', 2, 'header checking and data and index block checking', 'FALSE', 'false'),
(1485, 'recyclebin', 2, 'recyclebin processing', 'on', 'false'),
(1607, 'db_securefile', 2, 'permit securefile storage during lob creation', 'PERMITTED', 'false'),
(1650, 'create_stored_outlines', 2, 'create stored outlines for DML statements', '', 'false'),
(1653, 'serial_reuse', 2, 'reuse the frame segments', 'disable', 'false'),
(1661, 'ldap_directory_access', 2, 'RDBMS''s LDAP access option', 'NONE', 'false'),
(1662, 'ldap_directory_sysauth', 2, 'OID usage parameter', 'no', 'false'),
(1663, 'os_roles', 1, 'retrieve roles from the operating system', 'FALSE', 'false'),
(1664, 'rdbms_server_dn', 2, 'RDBMS''s Distinguished Name', '', 'false'),
(1665, 'max_enabled_roles', 3, 'max number of roles a user can have enabled', '150', 'false'),
(1666, 'remote_os_authent', 1, 'allow non-secure remote clients to use auto-logon accounts', 'FALSE', 'false'),
(1667, 'remote_os_roles', 1, 'allow non-secure remote clients to use os roles', 'FALSE', 'false'),
(1669, 'sec_case_sensitive_logon', 1, 'case sensitive password enabled for logon', '', 'false'),
(1670, 'O7_DICTIONARY_ACCESSIBILITY', 1, 'Version 7 Dictionary Accessibility Support', 'FALSE', 'false'),
(1672, 'remote_login_passwordfile', 2, 'password file usage parameter', '', 'false'),
(1673, 'license_max_users', 3, 'maximum number of named users that can be created in the database', '0', 'false'),
(1677, 'audit_sys_operations', 1, 'enable sys auditing', 'FALSE', 'false'),
(1680, 'global_context_pool_size', 2, 'Global Application Context Pool Size in Bytes', '', 'false'),
(1683, 'db_domain', 2, 'directory part of global database name stored with CREATE DATABASE', '', 'false'),
(1684, 'global_names', 1, 'enforce that database links have same name as remote database', 'FALSE', 'false'),
(1685, 'distributed_lock_timeout', 3, 'number of seconds a distributed transaction waits for a lock', '60', 'false'),
(1687, 'commit_point_strength', 3, 'Bias this node has toward not preparing in a two-phase commit', '1', 'false'),
(1690, 'global_txn_processes', 3, 'number of background global transaction processes to start', '1', 'false'),
(1697, 'instance_name', 2, 'instance name supported by the instance', 'p372', 'false'),
(1698, 'service_names', 2, 'service names supported by the instance', '', 'false'),
(1700, 'dispatchers', 2, 'specifications of dispatchers', '', 'false'),
(1701, 'shared_servers', 3, 'number of shared servers to start up', '0', 'false'),
(1702, 'max_shared_servers', 3, 'max number of shared servers', '', 'false'),
(1703, 'max_dispatchers', 3, 'max number of dispatchers', '', 'false'),
(1704, 'circuits', 3, 'max number of circuits', '', 'false'),
(1705, 'shared_server_sessions', 3, 'max number of shared server sessions', '', 'false'),
(1706, 'local_listener', 2, 'local listener', '', 'false'),
(1707, 'remote_listener', 2, 'remote listener', '', 'false'),
(1708, 'listener_networks', 2, 'listener registration networks', '', 'false'),
(1722, 'cursor_space_for_time', 1, 'use more memory in order to get faster execution', 'FALSE', 'false'),
(1723, 'session_cached_cursors', 3, 'Number of cursors to cache in a session.', '50', 'false'),
(1727, 'remote_dependencies_mode', 2, 'remote-procedure-call dependencies mode parameter', 'TIMESTAMP', 'false'),
(1728, 'utl_file_dir', 2, 'utl_file accessible directories list', '', 'false'),
(1729, 'smtp_out_server', 2, 'utl_smtp server and port configuration parameter', '', 'false'),
(1731, 'plsql_v2_compatibility', 1, 'PL/SQL version 2.x compatibility flag', 'FALSE', 'false'),
(1733, 'plsql_warnings', 2, 'PL/SQL compiler warnings settings', 'DISABLE:ALL', 'false'),
(1734, 'plsql_code_type', 2, 'PL/SQL code-type', 'INTERPRETED', 'false'),
(1736, 'plsql_debug', 1, 'PL/SQL debug', 'FALSE', 'false'),
(1737, 'plsql_optimize_level', 3, 'PL/SQL optimize level', '2', 'false'),
(1738, 'plsql_ccflags', 2, 'PL/SQL ccflags', '', 'false'),
(1740, 'plscope_settings', 2, 'plscope_settings controls the compile time collection, cross reference, and storage of PL/SQL source code identifier data', 'IDENTIFIERS:NONE', 'false'),
(1744, 'permit_92_wrap_format', 1, 'allow 9.2 or older wrap format in PL/SQL', 'TRUE', 'false'),
(1745, 'java_jit_enabled', 1, 'Java VM JIT enabled', 'TRUE', 'false'),
(1746, 'job_queue_processes', 3, 'maximum number of job queue slave processes', '1000', 'false'),
(1749, 'parallel_min_percent', 3, 'minimum percent of threads required for parallel query', '0', 'false'),
(1752, 'create_bitmap_area_size', 3, 'size of create bitmap buffer for bitmap index', '8388608', 'false'),
(1753, 'bitmap_merge_area_size', 3, 'maximum memory allow for BITMAP MERGE', '1048576', 'false'),
(1755, 'cursor_sharing', 2, 'cursor sharing mode', 'EXACT', 'false'),
(1758, 'result_cache_mode', 2, 'result cache operator usage mode', '', 'false'),
(1772, 'parallel_min_servers', 3, 'minimum parallel query servers per instance', '0', 'false'),
(1773, 'parallel_max_servers', 3, 'maximum parallel query servers per instance', '320', 'false'),
(1778, 'parallel_instance_group', 2, 'instance group to use for all parallel operations', '', 'false'),
(1782, 'parallel_execution_message_size', 3, 'message buffer size for parallel execution', '16384', 'false'),
(1793, 'hash_area_size', 3, 'size of in-memory hash work area', '131072', 'false'),
(1813, 'result_cache_max_size', 6, 'maximum amount of memory to be used by the cache', '', 'false'),
(1814, 'result_cache_max_result', 3, 'maximum result size as percent of cache size', '', 'false'),
(1815, 'result_cache_remote_expiration', 3, 'maximum life time (min) for any result using a remote object', '0', 'false'),
(1827, 'shadow_core_dump', 2, 'Core Size for Shadow Processes', 'partial', 'false'),
(1828, 'background_core_dump', 2, 'Core Size for Background Processes', 'partial', 'false'),
(1829, 'background_dump_dest', 2, 'Detached process dump directory', '/u01/app/oracle/diag/rdbms/p372_rz2/p372/trace', 'false'),
(1830, 'user_dump_dest', 2, 'User process dump directory', '/u01/app/oracle/diag/rdbms/p372_rz2/p372/trace', 'false'),
(1831, 'core_dump_dest', 2, 'Core dump directory', '/u01/app/oracle/diag/rdbms/p372_rz2/p372/cdump', 'false'),
(1840, 'audit_file_dest', 2, 'Directory in which auditing files are to reside', '', 'false'),
(1841, 'audit_syslog_level', 2, 'Syslog facility and level', '', 'false'),
(1847, 'object_cache_optimal_size', 3, 'optimal size of the user session''s object cache in bytes', '102400', 'false'),
(1848, 'object_cache_max_size_percent', 3, 'percentage of maximum size over optimal of the user session''s object cache', '10', 'false'),
(1852, 'session_max_open_files', 3, 'maximum number of open files allowed per session', '10', 'false'),
(1858, 'open_links', 3, 'max # open links per session', '4', 'false'),
(1859, 'open_links_per_instance', 3, 'max # open links per instance', '4', 'false'),
(1863, 'commit_write', 2, 'transaction commit log write behaviour', '', 'false'),
(1864, 'commit_wait', 2, 'transaction commit log wait behaviour', '', 'false'),
(1865, 'commit_logging', 2, 'transaction commit log write behaviour', '', 'false'),
(1867, 'optimizer_features_enable', 2, 'optimizer plan compatibility parameter', '11.2.0.3', 'false'),
(1868, 'fixed_date', 2, 'fixed SYSDATE value', '', 'false'),
(1869, 'audit_trail', 2, 'enable system auditing', 'none', 'false'),
(1870, 'sort_area_size', 3, 'size of in-memory sort work area', '65536', 'false'),
(1871, 'sort_area_retained_size', 3, 'size of in-memory sort work area retained between fetch calls', '0', 'false'),
(1885, 'cell_offload_processing', 1, 'enable SQL processing offload to cells', 'TRUE', 'false'),
(1886, 'cell_offload_decryption', 1, 'enable SQL processing offload of encrypted data to cells', 'TRUE', 'false'),
(1887, 'cell_offload_parameters', 2, 'Additional cell offload parameters', '', 'false'),
(1888, 'cell_offload_compaction', 2, 'Cell packet compaction strategy', 'ADAPTIVE', 'false'),
(1889, 'cell_offload_plan_display', 2, 'Cell offload explain plan display', 'AUTO', 'false'),
(1892, 'db_name', 2, 'database name specified in CREATE DATABASE', '', 'false'),
(1893, 'db_unique_name', 2, 'Database Unique Name', '', 'false'),
(1894, 'open_cursors', 3, 'max # cursors per session', '50', 'false'),
(1895, 'ifile', 4, 'include file in init.ora', '', 'false'),
(1896, 'sql_trace', 1, 'enable SQL trace', 'FALSE', 'false'),
(1897, 'os_authent_prefix', 2, 'prefix for auto-logon accounts', 'ops$', 'false'),
(1899, 'optimizer_mode', 2, 'optimizer mode', 'ALL_ROWS', 'false'),
(1904, 'sql92_security', 1, 'require select privilege for searched update/delete', 'FALSE', 'false'),
(1906, 'blank_trimming', 1, 'blank trimming semantics parameter', 'FALSE', 'false'),
(1912, 'star_transformation_enabled', 2, 'enable the use of star transformation', 'FALSE', 'false'),
(1918, '_optimizer_cost_model', 2, 'optimizer cost model', NULL, 'false'),
(1920, '_optimizer_system_stats_usage', 1, 'system statistics usage', NULL, 'false'),
(1954, 'parallel_degree_policy', 2, 'policy used to compute the degree of parallelism (MANUAL/LIMITED/AUTO)', 'MANUAL', 'false'),
(1962, 'parallel_adaptive_multi_user', 1, 'enable adaptive setting of degree for multiple user streams', 'TRUE', 'false'),
(1963, 'parallel_threads_per_cpu', 3, 'number of parallel execution threads per CPU', '2', 'false'),
(1964, 'parallel_automatic_tuning', 1, 'enable intelligent defaults for parallel execution parameters', 'FALSE', 'false'),
(1970, 'parallel_io_cap_enabled', 1, 'enable capping DOP by IO bandwidth', 'FALSE', 'false'),
(1990, '_optimizer_max_permutations', 3, 'optimizer maximum join permutations per query block', NULL, 'false'),
(1991, 'optimizer_index_cost_adj', 3, 'optimizer index cost adjustment', '100', 'false'),
(1992, 'optimizer_index_caching', 3, 'optimizer percent index caching', '0', 'false'),
(2004, 'query_rewrite_enabled', 2, 'allow rewrite of queries using materialized views if enabled', 'TRUE', 'false'),
(2005, 'query_rewrite_integrity', 2, 'perform rewrite using materialized views with desired integrity', 'enforced', 'false'),
(2061, 'pga_aggregate_target', 6, 'Target size for the aggregate PGA memory consumed by the instance', '', 'false'),
(2063, '_pga_max_size', 6, 'Maximum size of the PGA memory for one process', NULL, 'false'),
(2064, 'workarea_size_policy', 2, 'policy used to size SQL working areas (MANUAL/AUTO)', 'AUTO', 'false'),
(2084, 'optimizer_dynamic_sampling', 3, 'optimizer dynamic sampling', '2', 'false'),
(2114, 'statistics_level', 2, 'statistics level', 'TYPICAL', 'false'),
(2139, 'cursor_bind_capture_destination', 2, 'Allowed destination for captured bind variables', 'memory+disk', 'false'),
(2157, '_optimizer_search_limit', 3, 'optimizer search limit', NULL, 'false'),
(2158, 'skip_unusable_indexes', 1, 'skip unusable indexes if set to TRUE', 'TRUE', 'false'),
(2202, '_optimizer_join_order_control', 3, 'controls the optimizer join order search algorithm', NULL, 'false'),
(2238, 'optimizer_secure_view_merging', 1, 'optimizer secure view merging and predicate pushdown/movearound', 'TRUE', 'false'),
(2282, 'ddl_lock_timeout', 3, 'timeout to restrict the time that ddls wait for dml lock', '0', 'false'),
(2284, 'deferred_segment_creation', 1, 'defer segment creation to first insert', 'TRUE', 'false'),
(2292, 'optimizer_use_pending_statistics', 1, 'Control whether to use optimizer pending statistics', 'FALSE', 'false'),
(2297, 'optimizer_capture_sql_plan_baselines', 1, 'automatic capture of SQL plan baselines for repeatable statements', 'false', 'false'),
(2298, 'optimizer_use_sql_plan_baselines', 1, 'use of SQL plan baselines for captured sql statements', 'TRUE', 'false'),
(2319, 'parallel_min_time_threshold', 2, 'threshold above which a plan is a candidate for parallelization (in seconds)', 'AUTO', 'false'),
(2321, 'parallel_degree_limit', 2, 'limit placed on degree of parallelism', 'CPU', 'false'),
(2322, 'parallel_force_local', 1, 'force single instance execution', 'FALSE', 'false'),
(2331, 'optimizer_use_invisible_indexes', 1, 'Usage of invisible indexes (TRUE/FALSE)', 'FALSE', 'false'),
(2355, 'dst_upgrade_insert_conv', 1, 'Enables/Disables internal conversions during DST upgrade', 'TRUE', 'false'),
(2360, 'parallel_servers_target', 3, 'instance target in terms of number of parallel servers', '128', 'false'),
(2410, 'sec_protocol_error_trace_action', 2, 'TTC protocol error action', 'TRACE', 'false'),
(2411, 'sec_protocol_error_further_action', 2, 'TTC protocol error continue action', 'CONTINUE', 'false'),
(2412, 'sec_max_failed_login_attempts', 3, 'maximum number of failed login attempts on a connection', '10', 'false'),
(2413, 'sec_return_server_release_banner', 1, 'whether the server retruns the complete version information', 'FALSE', 'false'),
(2416, 'enable_ddl_logging', 1, 'enable ddl logging', 'FALSE', 'false'),
(2419, 'client_result_cache_size', 6, 'client result cache max size in bytes', '0', 'false'),
(2420, 'client_result_cache_lag', 6, 'client result cache maximum lag in milliseconds', '3000', 'false'),
(2443, 'aq_tm_processes', 3, 'number of AQ Time Managers to start', '1', 'false'),
(2459, 'hs_autoregister', 1, 'enable automatic server DD updates in HS agent self-registration', 'TRUE', 'false'),
(2460, 'xml_db_events', 2, 'are XML DB events enabled', 'enable', 'false'),
(2461, 'dg_broker_start', 1, 'start Data Guard broker (DMON process)', 'false', 'false'),
(2462, 'dg_broker_config_file1', 2, 'data guard broker configuration file #1', '', 'false'),
(2463, 'dg_broker_config_file2', 2, 'data guard broker configuration file #2', '', 'false'),
(2475, 'olap_page_pool_size', 6, 'size of the olap page pool in bytes', '0', 'false'),
(2571, 'asm_diskstring', 2, 'disk set locations for discovery', '', 'false'),
(2573, 'asm_preferred_read_failure_groups', 2, 'preferred read failure groups', '', 'false'),
(2583, 'asm_diskgroups', 2, 'disk groups to mount automatically', '', 'false'),
(2584, 'asm_power_limit', 3, 'number of parallel relocations for disk rebalancing', '1', 'false'),
(2655, 'control_management_pack_access', 2, 'declares which manageability packs are enabled', 'DIAGNOSTIC+TUNING', 'false'),
(2677, 'awr_snapshot_time_offset', 3, 'Setting for AWR Snapshot Time Offset', '0', 'false'),
(2681, 'sqltune_category', 2, 'Category qualifier for applying hintsets', 'DEFAULT', 'false'),
(2713, 'diagnostic_dest', 2, 'diagnostic base directory', '', 'false'),
(2737, 'tracefile_identifier', 2, 'trace file custom identifier', '', 'false'),
(2739, 'max_dump_file_size', 2, 'Maximum size (in bytes) of dump file', 'unlimited', 'false'),
(2742, 'trace_enabled', 1, 'enable in memory tracing', 'TRUE', 'false'),
(9001, 'NLS_CHARACTERSET', 2, 'database character set', 'WE8ISO8859P15', 'false'),
(9002, 'status', 2, 'dataguard status of the instance', 'OPEN', 'false'),
(9003, 'used_fra_space', 6, 'Used FRA space by the instance.', '', 'true'),
(9004, 'reclaimable_fra_space', 6, 'Reclaimable FRA space by the instance.', '', 'true'),
(9005, 'data_pump_dir_free_space', 3, 'Free space of data_pump_dir', NULL, 'true'),
(9006, 'data_pump_dir', 2, 'DATA_PUMP_DIR', '', 'false'),
(9007, '_sga_size', 3, '(in MB) Controls the amount of memory that the LogMiner processes (streams_pool) when they mine information from the ', '30', 'false'),
(9008, '_CHECKPOINT_FORCE', 2, 'Forces a Streams checkpoint', 'N', 'false');
